version: "2.4"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.25
    restart: always
    volumes:
      - ./sql-data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    hostname: USMIANAPAUTO
    environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'

# References:
# https://github.com/tutorialesvip/Docker-Compose-MySQL